# Generated by Django 4.2.1 on 2023-09-14 10:14

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=account.models.get_email, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
