# Generated by Django 4.2.5 on 2023-10-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
