# Generated by Django 4.2.1 on 2023-09-16 19:36

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_comment_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigIntegerField(default=account.models.get_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.BigIntegerField(default=account.models.get_id, primary_key=True, serialize=False),
        ),
    ]
